system electricBeamSystem
{
    technique 
    {
        keep_local                              true
        material                                ParticleUniverse/Lightning
        default_particle_width                  0.02
        default_particle_height                 0.02
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 Line
        {
            emission_rate                       200
            angle                               0
            time_to_live                        1
        }
        affector                                Align
        {
            resize                              true
        }
    }
}
