system electricBeamSystem
{
    technique 
    {
        keep_local                              true
        material                                BaseWhite
        default_particle_width                  0.1
        default_particle_height                 0.3
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 Point
        {
            emission_rate                       5
            angle                               0
            time_to_live                        0.25
            velocity                            2
            direction                           0 1 0
            colour                              1 0 0 0.2
        }

    }
}
